export default function Home() {
  return (
    <main className="flex items-center justify-center">
      <div>
        ganesh ganesh
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
        <h1>ganesh</h1>
      </div>
    </main>
  );
}
